In [ ]:
import numpy as np
import time

numpy is most important library used in machine learning for data arrangement

1.   numpy is used to arrange data in different dimesions(data arr)
2.   we use numpy for mathematical and statistical analysis
3.   working with numeric numbers



In [ ]:
dim0=np.array(100) # dim - dimension , array functin- to create array, '100'- a single elemet => zero dimensonal array because we store a single element in array.
dim0


array(100)

In [ ]:
dim0.ndim # (n means number , dim means dimension) ndim is attribute to check the dimensions of any variable or array
# output is 0 that means it is a zero dimensional array

0

In [ ]:
# dim0=np.array([100]) # here 100 element is not stored directly, it is stored in the list- list bnakr element ko store kar dia
# here it is 1 D not 0 D
# dim0
# dim0.ndim

#lets check wht if list is empty
#dim0=np.array([])
#dim0
#dim0.ndim #here also it is 1 D

ndim is a attribute of numpy not a function , agar function hota toh end me parenthesis hota

how will inner struture if zero dimensional array formed here will look like?

In [ ]:
dim0.shape # shape attribute of numpy is used to check the inner structure of the variable
# we got empty parenthesis, because it is a zero dim array - it has no axis
# conisder it like a single point - without any axis
# coz dimension bnna shuru hota hai x axis k sath

()

In [ ]:
dim1=np.array([1,5,8,4,7,5]) # ek array banake ek single list ko us variable me store kraya hai #dim1 is variable here
dim1

array([1, 5, 8, 4, 7, 5])

In [ ]:
dim1.ndim #to check dimension

1

In [ ]:
dim1.shape# to check shape
# output is 6, this 6 shows that ek variable mein aisa list store hai jisme 6 elements stored h
# here ',' means aage bhi kuch hoga,,, jab hm 2D bnaenge.

(6,)

In [ ]:
dim2=np.array([[1,6,7],[8,9,5],[5,7,1]]) #when multiple lists are stored in a variable - 2D array (matrix) is formed
# ab jese ek variable ke andar we cant store 3 values directly, uske lie hm array bnate hai...
# therefore hum teeno list ko ek list me store krenge - i.e, 3  lists se bna hua list is stored in dim2(variable)
dim2

array([[1, 6, 7],
       [8, 9, 5],
       [5, 7, 1]])

In [ ]:
dim2.ndim # check dimension

2

In [ ]:
dim2.shape # checking shape
# we get this output, that is, this dim2 variable have three different lists, and each list have 3 elements stored in it
# first 3 - number of lists, second 3 - number of elements in each list

(3, 3)

In [ ]:
dim3=np.array([[[3,8,9],[7,8,4]],[[1,5,7],[9,7,5]]]) # multiple 2D arrays (matrices) are stored in variable - we get a 3D array
# here also, just like, ek variable me 2 values ko directly nhi store kr paenge , so here 2 matrices ko hum ek aur list me store krenge.
dim3

array([[[3, 8, 9],
        [7, 8, 4]],

       [[1, 5, 7],
        [9, 7, 5]]])

In [ ]:
dim3.ndim # to check dimensions

3

In [ ]:
dim3.shape # to check the shape
# first 2 represents - two 2D arrays (matrices)
# second 2 represets - each 2D array have 2 lists
# third 3 represents - each list has 3 elements

(2, 2, 3)

Hence from here we conclude:


---
Agar ek variable banakr, usme hm

* ek array bnakr ek element ko store krenge - 0D
* ek list ko store krenge - 1D   
* multiple lists store krenge - 2D
* multiple 2D arrays ko store krenge - 3D  

(generally , practially array is not used in 3D)



In [ ]:
dim5=np.array([1,3],ndmin=5) # any dimensional array
# suppose we are asked to make 5 dimensional array, so we are given a 1D array - [1,3]
# here will pass an argument 'ndmin' which means "number of dimension in"

dim5

# hence this will result in 5Dimensional array.
# here we can see elements ke aound 5 layers h, so here dimensions means ki elements kitni layer ke andr stored h

array([[[[[1, 3]]]]])

In [ ]:
a2=[[[3,8,9],[7,8,4]],[[1,5,7],[9,7,5]]]
a2

[[[3, 8, 9], [7, 8, 4]], [[1, 5, 7], [9, 7, 5]]]

In [ ]:
start=time.time()
a=np.arange(100_00_00_00)
for i in range(len(a)):
  a[i]+=5
end=time.time()
req=end-start
req


45.899296045303345

In [ ]:
start=time.time()
a=np.arange(100_00_00_00)
a=a+5
end=time.time()
req=end-start
req



0.8898394107818604

In [ ]:
dim1 # this is 1 D array
# indexing krte hai

# index number - positional value - konsi position pr stored h

array([1, 5, 8, 4, 7, 5])

Indexing


*   Forward Indexing - left to right - from 0 index to nth.
Here in array from 1 to 5 agar jaye toh that is forward indexing.
 #### Here counting will begin from 0.

*   Backward Indexing / Negative Indexing - right to left - from nth to 0.
Here in arrat if we go from 5 to 1, it is backward indexing.
 #### Here counting will begin from -1.


In [ ]:
dim1[2]

np.int64(8)

In [ ]:
dim1[-4]

np.int64(8)

hence every element have two positional values, one from forward indexing another from backward, just like happens in python

In [ ]:
dim1=dim1+10 # will add10 to each elements of the array
dim1

array([11, 15, 18, 14, 17, 15])

In [ ]:
dim1

array([11, 15, 18, 14, 17, 15])

In [ ]:
dim1[-2] #negative indexing

np.int64(17)

In [ ]:
dim2 # in case of 2D array, locating any element
# here first list ki position 0, second ki 1,...

array([[1, 6, 7],
       [8, 9, 5],
       [5, 7, 1]])

In [ ]:
dim2[1,1] # first 1 indicates list1, sceond 1 indicates 1st index of list1

np.int64(9)

In [ ]:
#accessing the same thing via negative index
dim2[-2,-2]

np.int64(9)

In [ ]:
dim2[1,0:2] #slicing
# 0 is initaitaing value- khn sekatna shuru krrhe h, 2 is jhn pr khtm krenge katna
# hmne 8 and9 ko slice krke nikala h
# slicing ka rule ek jyada position lena pdta
#slicing means bade part me se chhota sa part niklana

array([8, 9])

In [ ]:
#via negative slicing
dim2[-2,-3:-1]

array([8, 9])

In [ ]:
dim2[1,1:] # 1 ke baad jitne b h slice krdo including that as well which is at 1

array([9, 5])

In [ ]:
dim3 #in case of 3D, locating an element
# 3 layered h - outermost layer- matrix stored h, then matrix me list stored hai, thn list me element milega

array([[[3, 8, 9],
        [7, 8, 4]],

       [[1, 5, 7],
        [9, 7, 5]]])

In [ ]:
dim3[1,0,1:]

array([5, 7])

In [ ]:
dim3[1,1,0]

np.int64(9)

In [ ]:
dim3[1,1,0]=10 #mutation
# suppose mujhe yhn 9 ki jgh 10 krna h - khn pr? second matrix ke second list ke first index(position) pr
# badalna h - replace krna h (mutation)
# so this is mutation
dim3 #printing updated dim3

array([[[ 3,  8,  9],
        [ 7,  8,  4]],

       [[ 1,  5,  7],
        [10,  7,  5]]])

In [ ]:
#z122[2,0,0]

In [ ]:
# ab tak jo bhi array bn rha tha, uske lie elements hmne khud bnaye the
# ab hum numbers manually nhi declare krenge, randomly bnaenge
a1=np.random.randint(100) # here a1 is variable , random - class name, randint function where rand- random and int - for integer
# koi bhi ek numeric number can either be integer(whole number) or float(decimal number)
# a random number can be from 0 to infinite
# therefore here max range is 100 and min range is 0, i.e, yahan 100 se jyada number print nhi hoga
a1 # output me random number print hoga but no greater than 100

66

In [ ]:
# but agar hm dekhe , kisi bhi ek project me agar hum random number bnakr kaam krenge toh everytime a new random number will be generated- jitni br bhi code ko run krenge
# this will reuslt in different outputs everytime
# but we want is random number toh generate ho, but vo jo number create horha h vo hmesha alag number na ho
# ek br randomly number generate hgya, uske baad jitni bar bi cell ko run kru, same number create ho
# for that we will lock reproductivity - for that we will use seed function
np.random.seed(1) # seed ko lock krne k lie we will pass a numeric number
# we passes 1 to lock seed, that means ek br number randomly generate hgya, fir uske baad vo same rhega
# ye 1 -ek particular seed number ko choose krleta h, 1 se konsa number choose hoga na ye phle se set h
# ab seed ko agr 2 krde, tb different number hoga, but firse run krenge toh same rhega
# ab seed number 6000 krdia, tb alag number hoga, but firse run krenge toh same rhega
# i.e, seed function hmesha ek argument ko lega jo ek numeric number h usse vo ye denote krke rkhega ki konsa number create hoga
a1=np.random.randint(100)
a1
# in case we dont pass any number in seed function, it wont work

37

In [ ]:
# for generating randomly float number
a2=np.random.rand() # rand - rand function ki speciallity ye hoti hai - its range lie between 0 to 1 - [0,1)
a2 #randomly float number is genearted - between o to 1

0.9971848109388686

In [ ]:
# for locking its reproductivity, seed krdenge
np.random.seed(3) # its like ab ye 3 number id bn gya h, is id me store rha - ki jb bhi koi seed function use krke is trah se run krega output 0.55.... hoga.
a2=np.random.rand()
a2

0.5507979025745755

In [ ]:
# now is random number se alag alag dimenions ke array bnane h

In [ ]:
# 1D Array
d1=np.random.randint(15,size=(10))
# d1 name ke variable ke andr randomly no. generate krke ek 1D array bnana h
# randint me max range is 15 here
# size argument is passed here - alag alag dimensions ke array bnane k lie - here it is 10
# that is yahn pr 10 randomly integer number create hoke, usse ek 1D array bna
d1

array([ 9,  3,  8,  8,  0,  5, 13,  3, 10, 11])

In [ ]:
# for 2D array
d2=np.random.randint(15,size=(3,5)) # 3 list bne aur hr list me 5 elements ho
d2

array([[ 9,  9, 10,  5,  7],
       [ 6,  0,  4, 12, 13],
       [ 7, 14,  8, 10,  1]])

In [ ]:
# for 3D array
d3=np.random.randint(15,size=(3,5,2)) # 3 2D array bne, hr 2D array me 5 list bne aur hr list me 2 elements ho
d3

array([[[10,  6],
        [ 2,  2],
        [12,  1],
        [ 3, 10],
        [ 5,  8]],

       [[14,  1],
        [13, 10],
        [ 8, 11],
        [14,  7],
        [ 8, 11]],

       [[ 1, 11],
        [ 0,  5],
        [ 4, 14],
        [ 1,  5],
        [14,  4]]])

In [ ]:
# for float numbers
b1=np.random.rand(3) # ab here rand function me range dene ki need hai nhi
# size argument dene ki lag se bi need nhi h - just pass directly
b1 # here 3 float numbers will be created
# 1D Array

array([0.97599542, 0.67238368, 0.90283411])

In [ ]:
# for 2D array
b2=np.random.rand(2,5) # creating a 2D array which has 2 lists and every list has 5 elements
b2

array([[0.84575087, 0.37799404, 0.09221701, 0.6534109 , 0.55784076],
       [0.36156476, 0.2250545 , 0.40651992, 0.46894025, 0.26923558]])

In [ ]:
# for 3D array
b3=np.random.rand(2,2,5) # creating a 3D array which has 2 2D arrays, each of which has 2 lists, where each list has 5 elements
b3

array([[[0.29179277, 0.4576864 , 0.86053391, 0.5862529 , 0.28348786],
        [0.27797751, 0.45462208, 0.20541034, 0.20137871, 0.51403506]],

       [[0.08722937, 0.48358553, 0.36217621, 0.70768662, 0.74674622],
        [0.69109292, 0.68918041, 0.37360012, 0.6681348 , 0.33984866]]])

# Now what about float numbers which lie outside the range from 0 to 1.
## how can we generate them?

In [ ]:
# for that we will create a uniform function
c1=np.random.uniform(1.5,12.5,(10)) # uniform function me range set krenge - 1.5,12.5
# 10 elements bnana h
c1
# 1D Array

array([ 7.80073257,  5.08387874,  6.39659554,  2.17681824,  4.16942964,
       12.18762867,  4.03642625,  9.10625262,  8.65524544,  9.46333053])

In [ ]:
c2=np.random.uniform(1.5,12.5,(2,5))
c2
# 2D Array

array([[6.72597472, 8.06330152, 2.23666366, 2.29818352, 3.68873629],
       [3.17047097, 2.60114779, 2.92223251, 7.58605505, 3.56596307]])

In [ ]:
c2=np.random.uniform(1.5,12.5,(2,5,2))
c2
# 3D Array

array([[[11.97311367,  8.99772957],
        [ 7.45121641,  9.27898661],
        [ 4.40275338, 11.69398253],
        [10.73112364,  9.48951448],
        [ 6.78263952, 10.76313504]],

       [[ 9.69227556,  8.76358497],
        [11.55372794,  8.4703212 ],
        [ 5.52534643,  7.5812903 ],
        [ 3.66018634,  3.61279526],
        [ 9.48236586, 10.13430374]]])

In [ ]:
f1=np.arange(5) # this arange function , 5 numbers ko 0-5 arrange krke 1-D array bnadega (by default - 1D array)
f1

array([0, 1, 2, 3, 4])

In [ ]:
# for 2D array
f2=np.arange(15).reshape(5,3) #reshape function is used
# reshape in a way - 2D - therefore 5,3 reprsents 5 lists which have three elements each.
f2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# for 3D array
f2=np.arange(30).reshape(2,5,3) #reshape function is used
# reshape in a way - 3D - therefore 2,5,3 reprsents 2 2D arrays 5 lists which have three elements each.
f2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [ ]:
np.random.randn(10)
# randn function minus tk b ja skta h (negative also)
# in this kisi b range me kuch b bn skta h

array([-0.1801878 , -1.14869046, -0.2617224 , -0.54647578,  0.11697458,
        0.41787753, -1.25912727,  2.20163972,  0.78854293,  1.19294367])

In [ ]:
np.random.randn(5, 10)
# here 2D array
# 5 lists me 10 elements
# so in this way randomly we can generate numbers, and alag alag dimensions ke array bna skte h

array([[-0.26049995, -1.08196788,  0.84529098,  1.29044416, -1.7735216 ,
        -0.16553826,  0.37179608,  0.12399172, -0.74006828, -0.11100907],
       [ 0.04999369,  0.56383677, -0.33582789,  0.34345702,  0.87308123,
        -1.08991005, -0.29804335,  0.74004134,  1.01229161, -0.87811496],
       [ 0.48444183, -0.84971216,  0.49327823,  0.74141899,  1.34580752,
        -0.83644784, -0.41935506, -0.81206664,  0.99657921, -0.21245916],
       [-1.20479405, -0.54019703,  0.6634043 , -0.52493532, -1.83790984,
        -0.1510628 ,  0.02445475,  0.02192558, -0.08818496, -0.12662486],
       [ 0.28488278,  0.27135218, -1.13679136, -0.95467019,  1.34267254,
        -2.35490523,  1.52416604,  0.19253784, -0.76746492,  1.22783377]])

the main class used here is random class.
randn, rand, randint, arange - jitne bhi randomly number bnane ka function h sb random class se derive hote h

radint - always positive dega, rest can be randomly negative too,
rand is also positvie form 0 to 1.
randn can be positive or negative,its range lies from - to +.

In [ ]:
dim2

array([[1, 6, 7],
       [8, 9, 5],
       [5, 7, 1]])

In [ ]:
# adding 10 to every element of dim2
dim2=dim2+10

# while python me loops chlane pdte, but here no need in numpy

in numpy, any mathematical or statistial formula applied in variable toh vo directly element me jakr apply hota h.....this is called broadcasting rule of numpy

In [ ]:
dim2 #hence numpy is 100 times faster than python

array([[11, 16, 17],
       [18, 19, 15],
       [15, 17, 11]])

In [ ]:
#python has a library named time
import time #measures time

In [ ]:
start_time = time.time() # time library ke andr se time function ko import kia
a1=np.arange(1000000) # 0 se is digit tk jitne bhi numbers honge, hr ek ke bare me baat horhi h...
for i in range(len(a1)): #ab ise ek range bnake , us range me jitne bhi elements h usme 10 add krrhe h
#used a loop(we r doing in python)
  a1[i]+=10 #want to add
end=time.time()
total_time=end-start_time #jitna time laga total= end(jitne time me kaam khtm hohra h) me se start time(jab kaam start hua tha) minus krdia
#after running it, its execution takes around 8-10 seconds(python)

In [ ]:
total_time

0.35989880561828613

In [ ]:
#doing the same task using numpy
start_time = time.time()
a1=np.arange(1000000)
a1=a1+10
end=time.time()
total_time=end-start_time
#broadcasting means direct application , where no loop or functon is there
#broadcasting means agar variable ke andr 1 lakh elements b store h, then individually every element is denoted by the variable
#agr variable ke andr ek lakh elements store h, and agr variable me kuch changes krenge toh vo changes hr ek element me hoga
#for example, ek variable me puri ek list store hai, then vo variable us list ko b denote krega and us list me stored hr ek elements ko b denote krega

In [ ]:
total_time # total time taken is less here

0.007109642028808594

therefore we use numpy(specialised version of python) instead of python