In [ ]:
import numpy as np

#### 1. A teacher stores the scores of 10 students in a 1D NumPy array. Write code to display the 1D array and print scores greater than 50.

In [ ]:
scores = np.array([60,20,40,95,100,80,45,85,90,95])
scores # displaying 1D array


array([ 60,  20,  40,  95, 100,  80,  45,  85,  90,  95])

In [ ]:
scores[scores > 50] # printing scores greater than 50

array([ 60,  95, 100,  80,  85,  90,  95])

In [ ]:
# diplaying both in single code block
print('all scores:', scores)
print('scores greater than 50:', scores[scores>50])

all scores: [ 60  20  40  95 100  80  45  85  90  95]
scores greater than 50: [ 60  95 100  80  85  90  95]


#### 2. Using the same scores array, find the mean score of the class.

In [ ]:
mean_score = np.mean(scores)
mean_score

np.float64(71.0)

3. Determine the median of the scores to check the central tendency.

In [ ]:
median_score = np.median(scores)
median_score

np.float64(82.5)

4. Find the mode of the scores to identify the most frequent score.

In [ ]:
# mode_score = np.mode(scores)
# mode_score
# -> throws error
# mode() is not part of NumPy (np).

# unique elements and their counts
unique, counts = np.unique(scores, return_counts=True)

# unique → all the distinct elements in the array. (sorted)
# counts → how many times each corresponding element occurs.

#unique = [20, 40, 45, 60, 80, 85, 90, 95, 100]
#counts = [1, 1, 1, 2, 1, 1, 1, 1, 1]


mode_score = unique[np.argmax(counts)]

# np.argmax(counts) - Finds the index of the maximum value in the counts array.
# unique[np.argmax(counts) - Retrieves the element from unique at that index.

mode_score

# if all the elements have the same count (1), then 'np.argmax(counts)' returns the first index, which is 0
# and hence unique[np.argmax(counts)] , retrieves the element from unique at that index.
# in that case - So: unique[0] = 20
# why 20 and not 60? even tho fisrt element toh 60 dia tha na array m
# this is coz np.unique() always returns a sorted array of unique values and we have to look that array only.


np.int64(95)

In [ ]:
#scoree = np.array([60,20,40,65,100,80,45,85,90,95])
#unique, counts = np.unique(scoree, return_counts=True)
#mode_score = unique[np.argmax(counts)]           # [20, 40, 45, 60, 65, 80, 85, 90, 95, 100]  ← sorted unique array
#mode_score

#output - np.int64(20)

#This doesn’t mean 20 is a true mode — it’s just the first number with the highest frequency (which is 1 for all values).
#So technically, there is no mode here.

In [ ]:
frequency = counts[np.argmax(counts)]
frequency # no of times it is occuring

np.int64(2)

In [ ]:
# using scipy
from scipy import stats
scores = np.array([60,20,40,95,100,80,45,85,90,95])
mode_value = stats.mode(scores, keepdims=True) # stats.mode(array)
mode_value

ModeResult(mode=array([95]), count=array([2]))

In [ ]:
# why the output is displayed like this
# we have asked python to just show the raw return value of the stats.mode() function.
# That function returns a ModeResult object, which contains:
# mode: the most frequent value(s) - here The most frequent value is 95
# count: how many times that value appeared - here It occurred 2 times

# now Why array([95]) instead of just 95
# Because scipy.stats.mode() always returns the result as a NumPy array, even if it contains just one value.
# This is done to support multidimensional data consistently.
# So:
# mode_value.mode → array([95])
# mode_value.count → array([2])
# To get the actual values, you will use:

mode = mode_value.mode[0]
count = mode_value.count[0]
mode

np.int64(95)

In [ ]:
count

np.int64(2)

#### 5. You are given a 2D NumPy array containing temperatures recorded over 4 weeks (rows) for 7 days (columns). Display the full array and the temperature of the second week.

In [ ]:
temperatures = np.array([
    [30, 32, 31, 33, 34, 35, 33],  # Week 1
    [31, 33, 34, 32, 30, 29, 28],  # Week 2
    [29, 28, 30, 32, 33, 31, 30],  # Week 3
    [34, 35, 36, 33, 32, 31, 30]   # Week 4
])

In [ ]:
temperatures.ndim # it is 2D

2

In [ ]:
temperatures[1]

array([31, 33, 34, 32, 30, 29, 28])

6. Find the highest temperature of the month using NumPy.

In [ ]:
max_temperature = np.max(temperatures)
max_temperature

np.int64(36)

7. Normalize all temperatures using Min-Max normalization formula.

formula for normalized temperature-

normalized_value= x - x min / x max - x min


Where:
x = original value, x min = minimum temperature, x max = maximum temperature


In [ ]:
min_temperature = np.min(temperatures) # since max_temperatures is already defined above

normalized_temperatures = (temperatures - min_temperature) / (max_temperature - min_temperature)

normalized_temperatures

array([[0.25 , 0.5  , 0.375, 0.625, 0.75 , 0.875, 0.625],
       [0.375, 0.625, 0.75 , 0.5  , 0.25 , 0.125, 0.   ],
       [0.125, 0.   , 0.25 , 0.5  , 0.625, 0.375, 0.25 ],
       [0.75 , 0.875, 1.   , 0.625, 0.5  , 0.375, 0.25 ]])

#### 8. Calculate the standard deviation of the temperature data.

In [ ]:
std_dev = np.std(temperatures)
std_dev

np.float64(2.098043306103502)

#### 9. A supermarket tracks stock of 3 products over 4 weeks and 5 categories. Represent this using a 3D NumPy array. Write code to access stock of 2nd product in week 3.

In [ ]:
np.random.seed(1) # also using seed to lock reproductivity
stock = np.random.randint(100, size=(3, 4, 5)) # stock of 3 products over 4 weeks and 5 categories

# Here, i am only giving one argument to randint, which is treated as the exclusive upper bound.
# So this is equivalent to: stock = np.random.randint(0, 100, size=(3, 4, 5))

stock
# Represented this using a 3D NumPy array.

array([[[37, 12, 72,  9, 75],
        [ 5, 79, 64, 16,  1],
        [76, 71,  6, 25, 50],
        [20, 18, 84, 11, 28]],

       [[29, 14, 50, 68, 87],
        [87, 94, 96, 86, 13],
        [ 9,  7, 63, 61, 22],
        [57,  1,  0, 60, 81]],

       [[ 8, 88, 13, 47, 72],
        [30, 71,  3, 70, 21],
        [49, 57,  3, 68, 24],
        [43, 76, 26, 52, 80]]])

In [ ]:
stock_spw3 = stock[1, 2, :] #Writing code to access stock of 2nd product in week 3.
stock_spw3

array([ 9,  7, 63, 61, 22])

 #### 10. Calculate the total stock of each product over all weeks and categories.

In [ ]:
# To calculate the total stock of each product over all weeks and categories,
# I need to sum along the last two axes (i.e., weeks and categories)

total_stock_per_product = np.sum(stock, axis=(1, 2))
# Sum over weeks (axis=1) and categories (axis=2)
total_stock_per_product

array([759, 985, 901])

 #### 11. A 1D NumPy array holds survey ratings (scale of 1–10) from 50 people. Find how many people rated more than 7.

In [ ]:
np.random.seed(2)
ratings = np.random.randint(1, 11, size=50) ## rating 1 to 10 inclusive, size = 50 people
ratings

array([ 9,  9,  7,  3,  9,  8,  3,  2,  6,  5,  5,  6,  8,  4,  7,  5,  4,
        8,  7,  2,  4,  6,  9,  5,  7,  4, 10,  3,  1,  5,  3,  5,  2,  8,
        9,  3, 10,  9,  8,  2,  7,  9,  6, 10, 10, 10,  4,  1,  1,  3])

In [ ]:
rated_above_7 = ratings[ratings > 7] # people who rated above 7
rated_above_7

array([ 9,  9,  9,  8,  8,  8,  9, 10,  8,  9, 10,  9,  8,  9, 10, 10, 10])

In [ ]:
len(rated_above_7) # total number of people who rated above 7

17

In [ ]:
# or directly we can do this:
count_above_7 = np.sum(ratings > 7) # here we directly find how many people rated more than 7
count_above_7

np.int64(17)

#### 12. Count how many people gave a neutral rating (rating == 5).

In [ ]:
neutral_ratings = ratings[ratings == 5]
len(neutral_ratings)

6

In [ ]:
# shorter way
count_neutral = np.sum(ratings == 5)
count_neutral

np.int64(6)

 13. Normalize the ratings between 0 and 1.

In [ ]:
# To normalize the ratings between 0 and 1, we can use the Min-Max normalization formula as mentioned above.
# Since this formula mathematically guarantees that every normalized value is in [0,1].
min_val = np.min(ratings)
max_val = np.max(ratings)
normalized_ratings = (ratings - min_val) / (max_val - min_val)
normalized_ratings

array([0.88888889, 0.88888889, 0.66666667, 0.22222222, 0.88888889,
       0.77777778, 0.22222222, 0.11111111, 0.55555556, 0.44444444,
       0.44444444, 0.55555556, 0.77777778, 0.33333333, 0.66666667,
       0.44444444, 0.33333333, 0.77777778, 0.66666667, 0.11111111,
       0.33333333, 0.55555556, 0.88888889, 0.44444444, 0.66666667,
       0.33333333, 1.        , 0.22222222, 0.        , 0.44444444,
       0.22222222, 0.44444444, 0.11111111, 0.77777778, 0.88888889,
       0.22222222, 1.        , 0.88888889, 0.77777778, 0.11111111,
       0.66666667, 0.88888889, 0.55555556, 1.        , 1.        ,
       1.        , 0.33333333, 0.        , 0.        , 0.22222222])

#### 14. A fitness app stores 7 days of step count for 5 users in a 2D array. Find the average steps per user.

In [ ]:
# A 2D array: Rows = users (5 users) ; Columns = days (7 days)
steps = np.array([
    [5000, 6000, 7000, 8000, 9000, 7500, 6500],  # User 1
    [4000, 4500, 5000, 5500, 6000, 5800, 6200],  # User 2
    [8000, 8500, 9000, 9500, 10000, 9800, 9700], # User 3
    [3000, 3200, 3500, 3700, 4000, 3900, 3600],  # User 4
    [7000, 7200, 7500, 7800, 8000, 7900, 7700]   # User 5
])
average_steps_per_user = np.mean(steps, axis=1)
# Compute average steps per user (mean along axis=1)
# axis=1 means: compute mean across columns (days), per row (user).
average_steps_per_user

array([7000.        , 5285.71428571, 9214.28571429, 3557.14285714,
       7585.71428571])

In [ ]:
avg_steps = np.mean(steps, axis=1).astype(int)
avg_steps # just truncated (chop decimals)

array([7000, 5285, 9214, 3557, 7585])

In [ ]:
avg_step = np.round(np.mean(steps, axis=1)).astype(int)
avg_step # here rounded integers

array([7000, 5286, 9214, 3557, 7586])

#### 15. Display the steps recorded on day 3 for all users.

In [ ]:
steps[:, 2]

array([7000, 5000, 9000, 3500, 7500])

#### 16. Identify users who walked more than 7000 steps on any day.

In [ ]:
more_than_7000 = steps[steps > 7000]
# This filters all individual values in the 2D array that are greater than 7000 — it gives a 1D array of values, not users.
len(more_than_7000) # while this just counts how many individual values are > 7000

# here I am just filtering values, not identifying which user (row) had them.

16

In [ ]:
# Correct approach for identifying users:
# To identify users (rows) who had any value > 7000,
more_than_7000 = np.any(steps > 7000, axis=1) # steps > 7000 → returns a boolean array where each value indicates if steps > 7000
# np.any(..., axis=1) → checks if any day for a user has value > 7000
user_indices = np.where(more_than_7000)[0] # np.where(...) → gets the indices of users who satisfy the condition
user_numbers = user_indices + 1
user_numbers

# output - It means users 1, 3, and 5 had at least one day with more than 7000 steps.

array([1, 3, 5])

#### 17. Record the results of 10 trials for 3 chemical samples using a 2D array. Calculate the mean result for each chemical.

In [ ]:
np.random.seed(5)

results = np.random.randint(50, size=(10, 3)) # size=(10, 3) → 10 trials × 3 chemicals
results
# rows represnting trials, colums repesenting chemical samples

array([[35, 14, 47],
       [38, 16,  9],
       [ 8, 36, 39],
       [27, 48, 30],
       [16,  7, 12],
       [15, 49, 39],
       [16, 27, 44],
       [13, 11,  1],
       [47, 30, 20],
       [22, 18,  9]])

In [ ]:
# calculating the mean result for each chemical
# calculating column-wise mean coz rows represnting trials and colums repesenting chemical samples
mean_results = results.mean(axis=0) # axis=0 → column-wise operation (i.e., per chemical)
mean_results

array([23.7, 25.6, 25. ])

#### 18. Determine which trial had the highest deviation from the mean for each sample.

To determine which trial had the highest deviation from the mean for each chemical sample (i.e., column), follow these steps:

---


*   Step 1: Calculate mean per chemical (column)
*   Step 2: Calculate absolute deviation from mean for each trial
*   Step 3: Find the index (trial) of the max deviation for each chemical

In [ ]:
mean_results = results.mean(axis=0)
deviation = np.abs(results - mean_results)
max_deviation_trials = np.argmax(deviation, axis=0)
max_deviation_trials

array([8, 5, 7])

output -
For Chemical 1 (first column), Trial 8 had the highest deviation from its mean.

For Chemical 2 (second column), Trial 5 had the highest deviation from its mean.

For Chemical 3 (third column), Trial 7 had the highest deviation from its mean.

 #### 19. A hospital records 3 vital signs for 2 patients over 5 days. Store this in a 3D array and retrieve the vitals for the first patient on day 4.

The hospital is tracking 3 health readings for each patient every day.

---

Examples of vital signs could be:

*   Blood Pressure (BP)
*   Heart Rate (HR)
*   Temperature (Temp)

---

There are:

2 patients → so 2 entries

5 days → for each patient

3 vitals per day

---
so 3D array shape will be
(patients, days, vitals) = (2, 5, 3)

In [ ]:
np.random.seed(5)
vitals = np.random.randint(60, size=(2, 5, 3)) # 2 patients, 5 days, 3 vitals
vitals

array([[[35, 14, 47],
        [38, 54, 16],
        [ 9,  8, 36],
        [39, 27, 48],
        [30, 16,  7]],

       [[12, 15, 49],
        [53, 39, 16],
        [27, 44, 13],
        [11,  1, 47],
        [30, 20, 22]]])

In [ ]:
# Retrieve vitals for the first patient (index 0) on day 4 (index 3).
retrieving = vitals[0, 3]
retrieving

array([39, 27, 48])

20. Find the mode of a particular vital sign for one patient across all days.

In [ ]:
# Let’s say we want the 2nd vital sign (index 1) of Patient 1 (index 0):
vital_sign_values = vitals[0, :, 1] # vitals[0, :, 1] → accesses the 2nd vital sign of patient 1 across all 5 days.
mode_result = stats.mode(vital_sign_values, keepdims=True)
mode_result.mode[0]

np.int64(8)

In [ ]:
mode_result.count[0] # frequency

np.int64(1)